language: python
  - "2.7"
  - "3.6"
sudo: required
before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip conda-build anaconda-client pytest-cov
  - pip install coveralls
  - conda build .
  - conda install --use-local pyosim
  - conda info -a
script:
  - pytest -v --cov=pyosim tests
after_success:
  - coveralls
